# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhLjXU0tpR0CShS35bipkhrX7o2VXUnd
"""

import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_excel("/content/Book1.xlsx")
mv=data["Temperature"].mean()
max=data["Temperature"].max()
min=data["Temperature"].min()
data=data.fillna(mv)
print("Average of temperature for a month:")
print(mv)
print("maximum temperature in given days:")
print(max)
print("minimum temperature in given days:")
print(min)
day=0
for i in data['Temperature']:
  if(i>mv):
    day=day+1
    mv1=data["Temperature"].mean()
print("number of days the temperature exceeded threshold is:",mv1,day)
plt.plot(data['Days'],data["Temperature"],label="YEAR-2023",color='yellow')
plt.legend(loc='best')
plt.title("Temperature in celsius for 30 days")
plt.show()